@startuml
start
:初始化团队信息;
note left
        团队人数、bug系数、改进系数
end note
:初始化员工信息;
note left
        团队绩效（含bug、改进）、bug数、bug类型
        （0 无 1测试 2开发 3兼有）;
        、改进点数、改进类型
        （0 无 1提出人 2解决人 3兼有）;
end note
if (是否有bug) then (有)
   :团队绩效+=根据bug类型*相应bug系数;
endif
if (是否有改进) then (有)
   :团队绩效+=改进点数*相应改进类型系数;
endif
:输出绩效成绩;
stop
@enduml