spring:
  application:
    name: fight
  profiles:
    active: dev
server:
  port: 8080

# eid, fp参数必须填写，具体请参考 wiki-常见问题
# 随意填写可能导致订单无法提交等问题
jd:
  eid: L4K26K26WN6WVUT2SHCXVGDX77PAOGPI4R2SRREJFUN4DIDSOLIBDUTUJUPX5IUK45IC3SEGZHAGINYK2VEM72NKSY
  fp: fa34aab56afb12d3c29c6e75dad178ff
  sku_id: 100012043978
  show_code: /Users/tom/DownLoads/showcode.png
  buy_time:
  DEFAULT_USER_AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
  random_useragent: false
  # 支付密码
  # 如果你的账户中有可用的京券（注意不是东券）或 在上次购买订单中使用了京豆，
  # 那么京东可能会在下单时自动选择京券支付 或 自动勾选京豆支付。
  # 此时下单会要求输入六位数字的支付密码。请在下方配置你的支付密码，如 123456 。
  # 如果没有上述情况，下方请留空。
  payment_pwd:

